name: Run .bat file on push to main

on:
  push:
    branches:
      - main

jobs:
  run-bat-file:
    runs-on: self-hosted  # Specify the self-hosted runner label here

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run .bat file
      run: |
        ./test.bat
